### ISSUE TITLE
Make fails with error, unable to find emscripten.h

### ISSUE THREAD

**Issue by jake-sl** [mihaip/infinite-mac#62]
I'm trying to get infinite-mac running locally, and running into some build issues. Unsure if I am not following instructions carefully enough, or if there's an actual problem.

Environment: Mac OS 12.4, M1 Processor, Docker 4.9.1.

After installing dependencies, building the docker image, and opening a shell to the docker image attached to my macemu path, I run the following command.

`macemujs_conf_cpu=1 macemujs_conf_native=1 ./_embuild.sh && make clean && make -j4`

Which eventually fails with an error that emscripten.h was not found:

`g++ -I./../include -I./. -I. -I./../uae_cpu -DHAVE_CONFIG_H  -DOS_linux -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -fno-merge-constants -fno-gcse-sm  -c macroman.cpp -o obj/macroman.o
g++ -I./../include -I./. -I. -I./../uae_cpu -DHAVE_CONFIG_H  -DOS_linux -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -fno-merge-constants -fno-gcse-sm  -c ./../dummy/serial_dummy.cpp -o obj/serial_dummy.o
g++ -I./../include -I./. -I. -I./../uae_cpu -DHAVE_CONFIG_H  -DOS_linux -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -fno-merge-constants -fno-gcse-sm  -c ./JS/ether_js.cpp -o obj/ether_js.o
g++ -I./../include -I./. -I. -I./../uae_cpu -DHAVE_CONFIG_H  -DOS_linux -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -fno-merge-constants -fno-gcse-sm  -c ./../dummy/scsi_dummy.cpp -o obj/scsi_dummy.o
./JS/ether_js.cpp:3:10: fatal error: emscripten.h: No such file or directory
    3 | #include <emscripten.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:220: obj/ether_js.o] Error 1
make: *** Waiting for unfinished jobs....`

**Comment by mihaip** [comment]
I likely broke this with https://github.com/mihaip/macemu/commit/73331d1d3c466da3384c30cbc64dc6a6e15d7fa7, ether_js.cpp should not be getting built in the initial pass. This will require some tweaking of the Makefile -- I'm currently traveling but I should be able to look into it this weekend.

**Comment by jake-sl** [comment]
Thanks for that info. By using one of the older versions of your fork of macemu, and resolving #63 I was able to build successfully.
